ORION-3548 Add support of imdsv2 tokens in ext_ip_dns checks
yandex/ch-tools pull request #55
Opened 2023-08-28 12:50 UTC by GrigoryPervakov

2023-08-28 13:55 UTC, ianton-ru requested changes

2023-08-28 17:47 UTC, GrigoryPervakov commented on ch_tools/monrun_checks/ext_ip_dns.py
> +        "http://169.254.169.254/latest/api/token",
Simpler :) there is no such feature in gcp

2023-08-29 12:22 UTC, ianton-ru approved these changes

2023-08-29 12:59 UTC, ekopanev approved these changes

2023-08-29 13:39 UTC, merged