Config file support
yandex/ch-tools pull request #77
Opened 2023-11-20 15:00 UTC by Alex-Burmak

2023-11-20 15:56 UTC, myrrc requested changes
LGTM but maybe we should add a test loading a custom config and also one loading an invalid config file (rights issue, non-existent issue, bad contents)?

2023-11-21 09:18 UTC, aalexfvk approved these changes

2023-11-23 11:36 UTC, myrrc commented
Tests will be added in a separate PR

2023-11-23 11:36 UTC, myrrc approved these changes

2023-11-23 11:36 UTC, merged